name:  'Chromatic Deployment'

# This actions is triggered only when files positioned specified following paths are changed
on: pull_request
  # pull_request:
    # paths:
    #   - 'src/app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VRT_RESULT_MESSAGE: 'No changes'

    steps:
      - uses: actions/checkout@v1

      - name: Remove existing file
        run: sudo rm -rf /home/runner/work/storybook-taskbox/storybook-taskbox/node_modules/chokidar2

      # Node.js version management
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          # cache: 'npm'
      - run: npm ci

      # Chromatic actions
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Post comment about Chromatic information to PR
      - name: Remove unnecessary path for Chromatic link
        id: storybook-url
        run: echo "::set-output name=URL::${STORYBOOK_URL//\/iframe.html/}"
        env:
          STORYBOOK_URL: ${{ steps.chromatic.outputs.storybookUrl }}

      - name: Detect UI changes from visual regression test results
        if: steps.chromatic.outputs.code == 1
        run: echo "vrt_result='Detect UI changes!!'" >> $GITHUB_ENV

      - name: Get datetime for now
        id: datetime
        run: echo "::set-output name=now::$(date)"
        env:
          TZ: Asia/Tokyo

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Storybook'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Visit the **Storybook** for this PR (updated for commit ${{ github.event.pull_request.head.sha }})
            <${{ steps.storybook-url.outputs.URL }}>
            <sub>Build URL: ${{ steps.chromatic.outputs.buildUrl }}</sub>
            <sub>(:fire: updated at ${{ steps.datetime.outputs.now }})</sub>
          edit-mode: replace
