name:  'Chromatic Deployment'

# This actions is triggered only when files positioned specified following paths are changed
on: pull_request
  # pull_request:
    # paths:
    #   - 'src/app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      vrt_result_message: ':green_circle: No changes'

    steps:
      - uses: actions/checkout@v1

      # Node.js version management
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          # cache: 'npm'
      - run: |
        sudo rm -rf /home/runner/work/storybook-taskbox/storybook-taskbox/node_modules/chokidar2
        npm ci

      # Chromatic actions
      - name: Chromatic manually
        run: |
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --junit-report

      - name: Confirm log file
        run: |
          cat chromatic-build-*.xml


