name:  'Chromatic Deployment'

# This actions is triggered only when files positioned specified following paths are changed
on: pull_request
  # pull_request:
    # paths:
    #   - 'src/app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set the value
        id: step_one
        run: |
            echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
            curl https://httpbin.org/json >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV

      - name: Get the value
        run: echo ${{ env.JSON_RESPONSE }}

      # Node.js version management
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          # cache: 'npm'
      - run: |
          sudo rm -rf /home/runner/work/storybook-taskbox/storybook-taskbox/node_modules/chokidar2
          npm ci

      # Chromatic actions
      - name: Chromatic manually
        run: |
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --junit-report --exit-zero-on-changes

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Confirm log
        run: cat chromatic-build-*.xml

      - name: Run original chromatic CLI script
        run: sh chromatic-build-log-xmllint.sh

      - name: Output chromatic results
        id: chromatic-result
        run: echo "::set-output name=result::$(cat result.md)"

      # PR comment
      - name: Get datetime for now
        id: datetime
        run: echo "::set-output name=now::$(date)"
        env:
          TZ: Asia/Tokyo

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Storybook'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Visit the :books: **Storybook** :books: for this PR (updated for commit ${{ github.event.pull_request.head.sha }})
            ${{ steps.chromatic-result.outputs.result }}
            <sub>(:fire: updated at ${{ steps.datetime.outputs.now }})</sub>
          edit-mode: replace



